name: Dependabot PR auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot_automerge:
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge dependabot PR
        # Only merge patch and minor updates
        # Major updates require manual review
        if: >-
          steps.metadata.outputs.update-type != 'version-update:semver-major' &&
          !contains(github.event.pull_request.title, 'REDUNDANT')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-close redundant PRs
        if: contains(github.event.pull_request.title, 'REDUNDANT')
        run: gh pr close "$PR_URL" --comment "Closed automatically as the update is redundant."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
